### ISSUE TITLE
Data errors

### ISSUE THREAD

**Issue by j127** [openmundi/build#1]
Thanks for making the script available. If you didn't see it, it looks like there are a few errors in the world.db file:

```sql
sqlite> SELECT title FROM countries WHERE continent_id=3; -- North America
Canada
United States
México [Mexico]
Greenland
Saint Pierre and Miquelon
```

**Comment by geraldb** [comment]
What's the error? Sorry don't see it. If you only want "sovereign" countries not dependent territorries than use / add the country flag / type (or exclude territorries).

**Comment by j127** [comment]
Sorry, maybe I am mistaken. I thought Greenland was an error (Denmark), but it looks like it's considered to be North America. (I think that people in the US generally think of it as being "in Europe".) I thought that Saint Pierre and Miquelon wasn't a country.

**Comment by geraldb** [comment]
See <https://en.wikipedia.org/wiki/Dependent_territory> and the source for the database is <https://github.com/openmundi/world.db/blob/master/north-america/countries_(terr).txt> for dependent countries/territories in north america.
